#!/usr/bin/env bash
set -euo pipefail

OUTPUT="docs/little-mester-full-context.md"
mkdir -p "$(dirname "$OUTPUT")"

echo "📦 Collating ALL Little Mester files for external LLM assistance..."

cat > "$OUTPUT" << 'HEADER'
# Little Mester: Complete Project Context for Self-Modification
> **Instructions for External LLM (Claude/Gemini)**: 
> This document contains the complete source code, configuration, and operational workflows of the "Little Mester" agent. Use this context to analyze, suggest improvements, or generate code changes for Little Mester itself. When proposing changes, always consider the existing skills, testing workflows, and architecture defined below.

## 1. Operational Workflows & Skills
HEADER

# Add skills
if [ -d "skills" ]; then
    for skill in skills/*.md; do
        echo "### $(basename "$skill")" >> "$OUTPUT"
        cat "$skill" >> "$OUTPUT"
        echo "" >> "$OUTPUT"
    done
fi

cat >> "$OUTPUT" << 'SECTION'
## 2. Project Structure & Configuration
SECTION

# Add config files, scripts, etc.
git ls-files | grep -E '\.(sh|yaml|yml|toml|json|md|txt)$' | while read -r file; do
    echo "## File: \`$file\`" >> "$OUTPUT"
    echo '```' >> "$OUTPUT"
    cat "$file" >> "$OUTPUT"
    echo '```' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'SECTION'
## 3. Core Agent Source Code
SECTION

# Add main source files (excluding scripts, docs, and the output file itself)
git ls-files | grep -vE '(scripts/|docs/|\.git/|node_modules/|'"$OUTPUT"')' | while read -r file; do
    echo "## File: \`$file\`" >> "$OUTPUT"
    echo '```' >> "$OUTPUT"
    cat "$file" >> "$OUTPUT"
    echo '```' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
done || true

cat >> "$OUTPUT" << 'SECTION'
## 4. Instructions for Modification
- Always preserve the TDD and regression prevention workflows.
- When adding new skills, follow the format in `skills/`.
- Ensure all changes are compatible with the existing Docker/compose setup.
- Update this context file after making changes to keep it accurate.

---
*Generated by `collate.sh` on $(date)*
SECTION

echo "✅ Full Little Mester context generated at $OUTPUT"
