#!/usr/bin/env bash
set -euo pipefail

# Configuration
OUTPUT_FILE="docs/little-mester-web-context.md"
SKILLS_DIR="skills"
CODEBASE_CONTEXT="codebase_context.md"
mkdir -p "$(dirname "$OUTPUT_FILE")"

echo "📦 Collating Little Mester Web Context..."

# Start the document with optimized LLM structure
cat > "$OUTPUT_FILE" << 'HEADER'
# Little Mester: Complete Context for Web LLMs (Claude/Gemini)
> **Instructions**: Copy and paste this entire document into your LLM web interface. It contains all necessary context, skills, and constraints to operate Little Mester effectively in a stateless or semi-stateless environment.

## 1. Role & Objective
Little Mester is an autonomous software engineering agent focused on high-quality, test-driven development with strict regression prevention. It operates under a TDD-first philosophy, ensuring all changes are covered by unit and integration tests before commitment.

## 2. Core Skills & Workflows
HEADER

# Dynamically inject all skills from the skills directory
if [ -d "$SKILLS_DIR" ]; then
    for skill_file in "$SKILLS_DIR"/*.md; do
        if [ -f "$skill_file" ]; then
            echo "### $(basename "$skill_file" .md)" >> "$OUTPUT_FILE"
            cat "$skill_file" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        fi
    done
else
    echo "*⚠️ Skills directory not found. Create 'skills/' and add .md files to enable dynamic injection.*" >> "$OUTPUT_FILE"
fi

# Append architecture & codebase context
cat >> "$OUTPUT_FILE" << 'SECTION'
## 3. Codebase Architecture & Structure
SECTION

if [ -f "$CODEBASE_CONTEXT" ]; then
    cat "$CODEBASE_CONTEXT" >> "$OUTPUT_FILE"
else
    echo "*ℹ️ Run `./collate.sh` to generate the latest codebase context first, or manually paste your architecture notes here.*" >> "$OUTPUT_FILE"
fi

# Append active task state (requires manual update or CI/CD hook)
cat >> "$OUTPUT_FILE" << 'SECTION'
## 4. Active Tasks & Recent Changes
> *Note: Update this section with current PRs, TODOs, or active feature branches before handing off to an external LLM.*

- **Current Focus**: [Describe current task or feature branch]
- **Recent Commits**: [List relevant hashes/messages]
- **Known Issues/Blockers**: [List any]

## 5. Execution Constraints & Guardrails
- Always follow the Testing & Regression Prevention Workflow.
- Never commit without passing both unit and integration tests.
- Prioritize integration tests for system stability, unit tests for logic correctness.
- If a test cannot be written, explicitly state why and propose a workaround.
- Ask for clarification if requirements are ambiguous or conflicting.

---
*Generated by `scripts/collate-web-context.sh` on $(date)*
SECTION

echo "✅ Web context generated at $OUTPUT_FILE"
echo "📋 Ready to paste into Claude/Gemini web UI."
